name: spccr
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - flask=3.0.3
  - pymongo=4.8.0
  - requests=2.32.3
  - flask-cors=3.0.10
  - numpy=1.26.4
  - pytorch
  - pip
  - pip:
      - flask-cors~=3.0.10
